<?php

use Illuminate\Database\Seeder;

class card_savings_banksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = \Carbon\Carbon::now();

        DB::table('card_savings_banks')->insert([
            'id' => '1',
            'bank_id' => '8',
            'bank_code' => '302100011000',
            'url' => 'bank-2017-06-29-11-42-12-595477142ae59.png',
            'bank_short_name' => 'CNCB',
            'bank_address_code' => '110102',
            'bank_name' => '中信银行',
            'bank_province' => '北京市',
            'bank_city' => '北京市',
            'bank_address' => '北京市',
            'order' => 1,
            'status' => 1,
            'created_at' => $now,
            'updated_at' => $now,
            'deleted_at' => null,
        ]);
        DB::table('card_savings_banks')->insert([
            'id' => '2',
            'bank_id' => '17',
            'bank_code' => '301290000007',
            'url' => 'bank-2017-06-29-14-08-59-5954997b2add5.png',
            'bank_short_name' => 'BCM',
            'bank_address_code' => '310115',
            'bank_name' => '交通银行',
            'bank_province' => '上海市',
            'bank_city' => '上海市',
            'bank_address' => '上海市',
            'order' => 1,
            'status' => 1,
            'created_at' => $now,
            'updated_at' => $now,
            'deleted_at' => null,
        ]);
        DB::table('card_savings_banks')->insert([
            'id' => '3',
            'bank_id' => '15',
            'bank_code' => '403100000004',
            'url' => 'bank-2017-06-29-11-44-19-59547793d0bcf.png',
            'bank_short_name' => 'PSBC',
            'bank_address_code' => '110102',
            'bank_name' => '中国邮政储蓄银行',
            'bank_province' => '北京市',
            'bank_city' => '北京市',
            'bank_address' => '北京市',
            'order' => 1,
            'status' => 1,
            'created_at' => $now,
            'updated_at' => $now,
            'deleted_at' => null,
        ]);
        DB::table('card_savings_banks')->insert([
            'id' => '4',
            'bank_id' => '4',
            'bank_code' => '102100099996',
            'url' => 'bank-2017-06-29-11-55-29-59547a31dabc6.png',
            'bank_short_name' => 'ICBC',
            'bank_address_code' => '110108',
            'bank_name' => '中国工商银行',
            'bank_province' => '北京市',
            'bank_city' => '北京市',
            'bank_address' => '北京市',
            'order' => 1,
            'status' => 0,
            'created_at' => $now,
            'updated_at' => $now,
            'deleted_at' => null,
        ]);
        DB::table('card_savings_banks')->insert([
            'id' => '5',
            'bank_id' => '9',
            'bank_code' => '309391000011',
            'url' => 'bank-2017-06-29-11-56-17-59547a6133ff7.png',
            'bank_short_name' => 'CIB',
            'bank_address_code' => '350102',
            'bank_name' => '兴业银行',
            'bank_province' => '福建省',
            'bank_city' => '福州市',
            'bank_address' => '福建省福州市',
            'order' => 1,
            'status' => 1,
            'created_at' => $now,
            'updated_at' => $now,
            'deleted_at' => null,
        ]);
        DB::table('card_savings_banks')->insert([
            'id' => '6',
            'bank_id' => '6',
            'bank_code' => '307584007998',
            'url' => 'bank-2017-06-29-11-56-35-59547a730284c.png',
            'bank_short_name' => 'PAB',
            'bank_address_code' => '440303',
            'bank_name' => '平安银行',
            'bank_province' => '广东省',
            'bank_city' => '深圳市',
            'bank_address' => '广东省深圳市',
            'order' => 1,
            'status' => 1,
            'created_at' => $now,
            'updated_at' => $now,
            'deleted_at' => null,
        ]);
        DB::table('card_savings_banks')->insert([
            'id' => '7',
            'bank_id' => '2',
            'bank_code' => '104100000004',
            'url' => 'bank-2017-06-29-11-56-53-59547a85e14bb.png',
            'bank_short_name' => 'BOC',
            'bank_address_code' => '110102',
            'bank_name' => '中国银行',
            'bank_province' => '北京市',
            'bank_city' => '北京市',
            'bank_address' => '北京市',
            'order' => 1,
            'status' => 1,
            'created_at' => $now,
            'updated_at' => $now,
            'deleted_at' => null,
        ]);
        DB::table('card_savings_banks')->insert([
            'id' => '8',
            'bank_id' => '10',
            'bank_code' => '303100000006',
            'url' => 'bank-2017-06-29-11-57-11-59547a978b75a.png',
            'bank_short_name' => 'CEB',
            'bank_address_code' => '110102',
            'bank_name' => '中国光大银行',
            'bank_province' => '北京市',
            'bank_city' => '北京市',
            'bank_address' => '北京市',
            'order' => 1,
            'status' => 1,
            'created_at' => $now,
            'updated_at' => $now,
            'deleted_at' => null,
        ]);
        DB::table('card_savings_banks')->insert([
            'id' => '9',
            'bank_id' => '7',
            'bank_code' => '308584000013',
            'url' => 'bank-2017-06-29-11-58-02-59547acaef5a8.png',
            'bank_short_name' => 'CMB',
            'bank_address_code' => '440304',
            'bank_name' => '招商银行',
            'bank_province' => '广东省',
            'bank_city' => '深圳市',
            'bank_address' => '广东省深圳市',
            'order' => 1,
            'status' => 1,
            'created_at' => $now,
            'updated_at' => $now,
            'deleted_at' => null,
        ]);
        DB::table('card_savings_banks')->insert([
            'id' => '10',
            'bank_id' => '1',
            'bank_code' => '105100000017',
            'url' => 'bank-2017-06-29-11-42-45-59547735cdf52.png',
            'bank_short_name' => 'CCB',
            'bank_address_code' => '110102',
            'bank_name' => '中国建设银行',
            'bank_province' => '北京市',
            'bank_city' => '北京市',
            'bank_address' => '北京市',
            'order' => 1,
            'status' => 1,
            'created_at' => $now,
            'updated_at' => $now,
            'deleted_at' => null,
        ]);
        DB::table('card_savings_banks')->insert([
            'id' => '11',
            'bank_id' => '3',
            'bank_code' => '103100000026',
            'url' => 'bank-2017-06-29-11-58-28-59547ae47ef76.png',
            'bank_short_name' => 'ABC',
            'bank_address_code' => '110108',
            'bank_name' => '中国农业银行',
            'bank_province' => '北京市',
            'bank_city' => '北京市',
            'bank_address' => '北京市',
            'order' => 1,
            'status' => 0,
            'created_at' => $now,
            'updated_at' => $now,
            'deleted_at' => null,
        ]);
        DB::table('card_savings_banks')->insert([
            'id' => '12',
            'bank_id' => '12',
            'bank_code' => '304100040000',
            'url' => 'bank-2017-06-29-11-58-45-59547af5992bd.png',
            'bank_short_name' => 'HXB',
            'bank_address_code' => '110101',
            'bank_name' => '华夏银行',
            'bank_province' => '北京市',
            'bank_city' => '北京市',
            'bank_address' => '北京市',
            'order' => 1,
            'status' => 0,
            'created_at' => $now,
            'updated_at' => $now,
            'deleted_at' => null,
        ]);
        DB::table('card_savings_banks')->insert([
            'id' => '13',
            'bank_id' => '5',
            'bank_code' => '305100000013',
            'url' => 'bank-2017-06-29-11-59-02-59547b06a1c41.png',
            'bank_short_name' => 'CMBC',
            'bank_address_code' => '110101',
            'bank_name' => '民生银行',
            'bank_province' => '北京市',
            'bank_city' => '北京市',
            'bank_address' => '北京市',
            'order' => 2,
            'status' => 1,
            'created_at' => $now,
            'updated_at' => $now,
            'deleted_at' => null,
        ]);
    }
}
